### PR TITLE
Motor Coord included in ideal maths

### PR DESCRIPTION
**Pull request by mattdanby**

### CODE REVIEW

**Comment by AfdhalAtiffTan** [comment]
can this be used with mm units?

**Comment by mattdanby** [comment]
No, metres as the motor coordinates are used in the tension calculations for which they're in SI units

**Comment by AfdhalAtiffTan** [comment]
It is non-trivial to allow modbus_regs to accept floating point values, it would be nice if you can add a simple 1000 multiplier.

**Comment by mattdanby** [comment]
I'm sorry, but the units you're using are confusing me. Are the coordinates stored in metres for the payload?

**Comment by mattdanby** [comment]
I'm assuming they're all in mm now?

**Comment by AfdhalAtiffTan** [comment]
yes, all measurements are in mm.

**Comment by mattdanby** [comment]
Are all the modbus_regs type double then?

**Comment by AfdhalAtiffTan** [comment]
No, modbus only support 16-bit variables, I use ints extensively.

For example modbus_holding_regs[Target_Length_Winch0] is in 16-bit int (in mm).

You can see the declaration at the bottom of modbus_regs.h

**Pull request closed without merging**
